fix: verify version download (#12)
* pin checkout action

- match renovate syntax to uds-core
- update to newest version in github action

Signed-off-by: catsby <clint@defenseunicorns.com>

* - fail if we can't download the version
- correctly check for pre-step failure

Signed-off-by: catsby <clint@defenseunicorns.com>

* remove renovate tag on intentionally bad version

Signed-off-by: catsby <clint@defenseunicorns.com>

* try without -f

Signed-off-by: catsby <clint@defenseunicorns.com>

* try without -f

Signed-off-by: catsby <clint@defenseunicorns.com>

* try with -f and an ||

Signed-off-by: catsby <clint@defenseunicorns.com>

---------

Signed-off-by: catsby <clint@defenseunicorns.com>

diff --git a/.github/workflows/setup-uds.yaml b/.github/workflows/setup-uds.yaml
--- a/.github/workflows/setup-uds.yaml
+++ b/.github/workflows/setup-uds.yaml
@@ -16,7 +16,7 @@ jobs:
         os: [ubuntu-latest, macos-latest]
     runs-on: ${{ matrix.os }}
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
       - name: Setup UDS CLI with defaults
         uses: ./
@@ -29,13 +29,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
       - name: Setup UDS CLI
         uses: ./
         with:
-          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli extractVersion="^v(.*)$" versioning=semver-coerced
-          version: v0.16.0
+          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
+          version: v0.20.0
 
       - name: UDS CLI Version
         run: uds version
@@ -50,3 +50,28 @@ jobs:
 
       - name: List installed packages
         run: uds zarf package list
+
+  test-error-version:
+    name: Verify error on bad/unavailable version
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
+      - name: Setup UDS CLI with defaults
+        id: error_step
+        uses: ./
+        with:
+          version: v0.01.9
+        continue-on-error: true  # Allow the workflow to continue after failure
+
+      - name: The demo step has failed
+        if: ${{ always() }}
+        shell: bash
+        run: |
+          #!/bin/bash
+          if [ "${{ steps.error_step.outcome }}" != "failure" ]; then
+            echo "Expected the step to fail, but it did not!"
+            exit 1
+          else
+            echo "The step failed as expected."
+          fi
diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -53,7 +53,10 @@ runs:
         esac
 
         echo "Downloading UDS CLI ${version} for ${{ runner.os }} ${arch}"
-        curl -sL "${release_path}/uds-cli_${version}_${filename}" -o "${target_dir}/uds"
+        curl -f -sL "${release_path}/uds-cli_${version}_${filename}" -o "${target_dir}/uds" || {
+          echo "Error: curl failed to fetch ${version}_${filename}-${arch}"
+          exit 1
+        }
         chmod +x "${target_dir}/uds"
 
 
